version: '3.8'

services:

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "5432:5432"
    environment:
      MYSQL_PASSWORD: example

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_DB_SERVER_ADDRESS=db"
      - "MYSQL_DB_SERVER_PORT=5432"
      - "MYSQL_USER=MYSQL"
      - "MYSQL_PASSWORD=example"
    depends_on:
      - db
